# Generated by Django 2.2.3 on 2019-07-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190728_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='This is the description', help_text='Max of 250 Characters', max_length=250),
            preserve_default=False,
        ),
    ]
